version: "3"
services:
  front:
    build:
      context: front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_ENDPOINT=http://localhost:8080

  back:
    build:
      context: back
      dockerfile: Dockerfile.dev
    volumes:
      - ./back:/app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
