version: "3"
services:
  front:
    build: front
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    environment:
      - API_ENDPOINT=http://localhost:8080

  back:
    build: back
    volumes:
      - ./back:/app
    ports:
      - 8080:8080
    environment:
      - PORT=8080
