version: "3"
services:
  front:
    build: front
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - API_ENDPOINT=http://localhost:8080

  back:
    build: back
    ports:
      - 8080:8080
    environment:
      - PORT=8080
